version: "3.7"

services:
  db:
    container_name: video_downloader_db
    image: postgres:10.1-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: video_downloader_backend
    restart: always
    image: oma256/video-downloader
    command: docker/django/start.sh
    volumes:
      - .:/app
      - staticfiles:/opt/video_converter/staticfiles
      - media:/opt/video_converter/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  staticfiles:
  media: