version: "3.7"

services:
  db:
    container_name: converter_db
    image: postgres:10.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: converter_backend
    restart: always
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: docker/django/start.sh
    volumes:
      - .:/apps
      - staticfiles:/opt/video_converter/staticfiles
      - media:/opt/video_converter/media
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db


volumes:
  postgres_data:
  staticfiles:
  media: