# Generated by Django 2.1.3 on 2019-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_converter', '0002_auto_20190508_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='url',
            field=models.URLField(max_length=500, verbose_name='video link'),
        ),
    ]
